name: Linux Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["13"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn dist:pr
        env:
          CI: true
          
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: WeakAuras-Companion-PR
          path: |
            dist_electron/*.AppImage
            dist_electron/*.snap
            dist_electron/*.deb
            dist_electron/*.rpm
