name: Linux Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["13"]

    steps:
      - name: "Install Apt Dependencies"
        run: "sudo apt-get install -y rpmbuild"

      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn
        env:
          CI: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn dist:pr
        env:
          CI: true

      - name: Package Artifacts
        run: |
          mkdir artifact-appimage
          mv dist_electron/*.AppImage artifact-appimage/ || true
          mkdir artifact-snap
          mv dist_electron/*.snap artifact-snap/ || true
          mkdir artifact-deb
          mv dist_electron/*.deb artifact-deb/ || true
          mkdir artifact-rpm
          mv dist_electron/*.rpm artifact-rpm/ || true

      - uses: actions/upload-artifact@v2
        name: Upload AppImage
        with:
          name: WeakAuras-Companion-PR-Node${{ matrix.node }} AppImage
          path: artifact-appimage

      - uses: actions/upload-artifact@v2
        name: Upload Snap
        with:
          name: WeakAuras-Companion-PR-Node${{ matrix.node }} snap
          path: artifact-snap

      - uses: actions/upload-artifact@v2
        name: Upload deb
        with:
          name: WeakAuras-Companion-PR-Node${{ matrix.node }} deb
          path: artifact-deb

      - uses: actions/upload-artifact@v2
        name: Upload rpm
        with:
          name: WeakAuras-Companion-PR-Node${{ matrix.node }} rpm
          path: artifact-rpm
